# This is a basic workflow to help you get started with Actions

name: Make-Packages

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'v3.14'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: tar -czvf text.tar.gz text
      - run: tar -czvf json.tar.gz json
      - run: tar -czvf jsonld.tar.gz jsonld
      - run: tar -czvf template.tar.gz template
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "text.tar.gz,json.tar.gz,jsonld.tar.gz,template.tar.gz"
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
